### ISSUE TITLE
BUG: "Remove" from context menu on CTRLs built from rig profile JSON doesn't maintain outside keys

### ISSUE THREAD

**Issue by TheSleepyDino** [V1Interactive/FreeformTools#44]
Overdrivers built when you use a rigging profile JSON doesn't maintain keys outside Time Range when using the "Remove" on context menu.
1. Choose a rig profile JSON that contains overdrivers.
2. Set bake settings to "Time Range"
3. Animate an OD
4. Shorten the time range to test.
5. Ctrl + Alt + LMB > Rig Commands > Remove

You'll notice that the keys outside of the framed time range are deleted.

**Comment by zahmbie** [comment]
I couldn't repro this, working on Rick's Baqir character I rigged the left and right arm in FK, created an overdriver from the left shoulder to drive the right shoulder and saved that as a rigging json.  When I re-loaded it and animated the overdriver and removed it with a small frame time range it preserved the outside keys.

Can you send me character/rig files on Slack to test with?  If you put em here they'll be too public.

**Comment by TheSleepyDino** [comment]
I sent a link with the files.

**Comment by zahmbie** [comment]
I figured out what's going on here and we should chat about a solution that makes sense.  If the overdrivers are applied to a control with no animation, like a fresh rig file, there are no outside keys on the controls to preserve.  But I did find another issue while looking at this where the tools were forcing a full keyframe bake when using bake and remove on overdrivers.  The fix is to follow your settings if you are Only removing overdrivers, but if you're removing any base component along with the overdrivers it will force the full keyframe bake to make sure the skeleton has all of the rig's animation.
